function txt = setup2text(setup,cfg)
basedir = strrep(setup.basedir,'\','/');

txt = [ 'Setupinfo:\n' 'basedir ' basedir '\n' 'epochtime ' num2str(setup.epochtime) '\n' 'baseline ' num2str(setup.baseline) '\n' ...
       'suffix ' cfg.suffix '\n' 'prefix ' setup.prefix '\n' 'stat_kats ' num2str(setup.stat_kats) '\n' ...
       'stat_opak ' num2str(cell2mat(setup.stat_opak)) '\n' 'subfolder ' setup.subfolder '\n' ...
       'srovnejresp ' num2str(cfg.srovnejresp) 'podilcasuodpovedi ' num2str(cfg.podilcasuodpovedi) 'freqepochs' num2str(cfg.freqepochs) '\n\n' ...
];

end